[build]
target = "thumbv7em-none-eabihf"
rustflags = [
    # Standard linker, but is problematic for us
    # "-C", "link-arg=-Tlink.x", "-g"
    "-C", "link-arg=--nmagic",
    "-C", "linker=arm-none-eabi-ld",
    
]